[package]
name = "fields"
type = "lib"
authors = [""]
compiler_version = ">=0.31.0"

[dependencies]
# bigint = { tag="v0.2.0", git = "https://github.com/shuklaayush/noir-bigint", directory = "crates/biguint" }
